version: '3'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - 5432:5432
  cache:
    image: redis:4
    ports:
    - 6379:6379
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock